;!knitout-2
;;Machine: SWG091N2
;;Gauge: 5
;;Width: 250
;;Carriers: 1 2 3 4 5 6 7 8 9 10
;;Position: Center
inhook  1 ;
tuck - f9 1 
tuck - f5 1 
tuck - f1 1 
tuck + b2 1 
tuck + b6 1 
tuck + b10 1 
releasehook  1 ;
tuck - f7 1 
tuck - f3 1 
tuck + b4 1 
tuck + b8 1 
knit - f9 1 
knit - f7 1 
knit - f5 1 
knit - f3 1 
knit - f1 1 
knit + b2 1 
knit + b4 1 
knit + b6 1 
knit + b8 1 
knit + b10 1 
knit - f9 1 
knit - f7 1 
xfer f7 b7 
rack -2 
xfer b7 f5 
rack 0 
knit - f5 1 
knit - f3 1 
knit - f1 1 
knit + b2 1 
knit + b4 1 
knit + b6 1 
knit + b8 1 
knit + b10 1 
knit - f9 1 
inhook  2 ;
tuck - f23 2 
tuck - f21 2 
tuck - f19 2 
tuck - f17 2 
tuck - f15 2 
tuck + f14 2 
tuck + f16 2 
tuck + f18 2 
tuck + f20 2 
tuck + f22 2 
releasehook  2 ;
knit - f23 2 
knit - f22 2 
knit - f21 2 
knit - f20 2 
knit - f19 2 
knit - f18 2 
knit - f17 2 
knit - f16 2 
knit - f15 2 
knit - f14 2 
knit + f14 2 
knit + f15 2 
knit + f16 2 
knit + f17 2 
knit + f18 2 
knit + f19 2 
knit + f20 2 
knit + f21 2 
knit + f22 2 
knit + f23 2 
knit - f5 2 
knit - f3 2 
knit - f1 2 
knit + b2 2 
knit + b4 2 
knit + b6 2 
knit + b8 2 
knit + b10 2 
knit - f9 2 
tuck - f7 2 
knit - f5 2 
knit - f3 2 
knit - f1 2 
knit + b2 2 
knit + b4 2 
knit + b6 2 
knit + b8 2 
knit + b10 2 
knit - f9 2 
knit - f7 2 
knit - f5 2 
knit - f3 2 
knit - f1 2 
knit + b2 2 
knit + b4 2 
knit + b6 2 
knit + b8 2 
knit + b10 2 
knit - f9 2 
knit - f7 2 
knit - f5 2 
knit - f3 2 
knit - f1 2 
knit + b2 2 
knit + b4 2 
knit + b6 2 
knit + b8 2 
knit + b10 2 
knit - f9 2 
knit - f7 2 
knit - f5 2 
knit - f3 2 
knit - f1 2 
knit + b2 2 
knit + b4 2 
knit + b6 2 
knit + b8 2 
knit + b10 2 
outhook  1 ;
outhook  2 ;
drop f1 
drop b2 
drop f3 
drop b4 
drop f5 
drop b6 
drop f7 
drop b8 
drop f9 
drop b10 
drop f14 
drop f15 
drop f16 
drop f17 
drop f18 
drop f19 
drop f20 
drop f21 
drop f22 
drop f23 
